# Generated by Django 3.2.5 on 2021-10-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=256)),
                ('image_url', models.CharField(max_length=1024)),
            ],
        ),
    ]
